### ISSUE TITLE
Please add a readable github.io link to the repository description (appears at the top)

### ISSUE THREAD

**Issue by Fak3** [w3c-dvcg/lds-merkle-proof-2019#4]
Please add [a link to rendered html github page](https://w3c-dvcg.github.io/lds-merkle-proof-2019/) to the project description, as other dvcg repos do. For example see https://github.com/w3c-dvcg/lds-ecdsa-secp256k1-2019 repo which has a link at the top that you can follow.

**Comment by AnthonyRonning** [comment]
Done, thanks!
